export const ObjectsData = [
  {
    id: 1,
    navigation_id: "999",
    images: [""],
    polygon: [
      [26.352498, -23.642578],
      [28.22697, -29.267578],
      [29.305561, -29.267578],
      [29.916852, -27.070313],
      [29.993002, -26.71875],
      [30.977609, -26.630859],
      [33.651208, -15.644531],
      [33.578015, -13.886719],
      [33.063924, -11.777344],
      [29.688053, -11.513672],
      [28.459033, -15.908203],
      [28.381735, -15.644531],
      [27.839076, -17.753906],
      [27.994401, -18.017578],
    ],
    uz: {
      name: "5 o'quv binolari",
      videos: ["https://youtu.be/NlWK5kJWFgA"],
      building_info: "",
      deskription:
        "TIQXMMI ning asosiy 4 ta o’quv binosidan biri bo’lib, bu bino 2019-yilda qurilib foydalanishga topshirilgan. O’quv binosi 4 ta qavatdan iborat va shu jumladan ?? ta amaliyot va ?? ta laboratoriya xonalarini o’z ichiga oladi. Binoda bitta fakultet ya’ni “yer resurslarini boshqarish” fakulteti joylashgan. Bu fakultet 1945-yilda Toshkent irrigatsiya va qishloq xoʻjaligini mexanizatsiyalash injenerlari instituti (TIQXMII) tarkibida “Yer tuzish” nomi bilan tashkil etilgan. Fakultet 2004-yildan 2018-yilga qadar “Yerdan foydalanish va yer kadastri” nomi bilan faoliyat koʻrsatgan. Oʻzbekiston Respublikasi Prezidentining 2018-yil 8-maydagi 3702-sonli qaroriga asosan hozirda “Yer resurslarini boshqarish ” nomi bilan faoliyat koʻrsatib kelmoqda. Bugungi kunda fakultetda “Yerdan foydalanish”, “Geodeziya va geoinformatika”, “Davlat kadastrlari” va “Oliy matematika” kafedralari mavjud. Fakultetda yer tuzish va yer kadastri, geodeziya va kartografiya sohalari boʻyicha ishlab chiqarish bilan uzviy aloqalarni taʼminlash, talabalarga bilim berish va professor - oʻqituvchilarning malakasini oshirish hamda moddiy-texnik bazasini mustahkamlash, shuningdek oʻquv va ishlab chiqarish amaliyotlarini tashkil qilish maqsadida “Davlat soliq qo’mitasi huzuridagi kadastr agentligi” va uning tizimidagi korxona va tashkilotlar bilan hamkorlikda oʻquv, ilmiy-tadqiqot ishlari amalga oshirilmoqda.",
    },
    en: {
      name: "5 education building",
      videos: ["https://youtu.be/NlWK5kJWFgA"],
      building_info: "",
      deskription:
        "It is one of the 4 main educational buildings of TIQXMMI, and this building was built and commissioned in 2019. The educational building consists of 4 floors and includes ?? ta practice and ?? includes laboratory rooms. There is one faculty in the building, the faculty of 'land resources management'. This faculty was established in 1945 as part of the Tashkent Institute of Irrigation and Agricultural Mechanization Engineers (TIQXMII) under the name 'Earth Construction'. From 2004 to 2018, the Faculty operated under the name 'Land Use and Land Cadastre'. According to the decision of the President of the Republic of Uzbekistan No. 3702 dated May 8, 2018, it is currently operating under the name 'Land Resources Management'. Today, the faculty has 'Land use', 'Geodesy and geoinformatics', 'State cadastres' and 'Higher mathematics' departments. 'State Tax Committee' in order to ensure organic relations with production in the fields of land surveying and land cadastre, geodesy and cartography at the faculty, to educate students and improve the qualifications of professors and teachers, and to strengthen the material and technical base, as well as to organize educational and production practices Cadastre Agency' and in cooperation with enterprises and organizations in its system, educational and scientific research works are being carried out.",
    },
    ru: {
      name: "5 учебный корпус",
      videos: ["https://youtu.be/NlWK5kJWFgA"],
      building_info: "",
      deskription:
        "Это один из 4 основных учебных корпусов TIQXMMI, и это здание было построено и сдано в эксплуатацию в 2019 году. Учебный корпус состоит из 4 этажей и включает в себя ?? та практика и ?? включает лабораторные помещения. В корпусе находится один факультет, факультет «Управление земельными ресурсами». Этот факультет был создан в 1945 году в составе Ташкентского института инженеров ирригации и механизации сельского хозяйства (ТИМИМСХ) под названием «Земляное строительство». С 2004 по 2018 год факультет работал под названием «Землепользование и земельный кадастр». Согласно постановлению Президента Республики Узбекистан №3702 от 8 мая 2018 года, в настоящее время действует под наименованием «Управление земельными ресурсами». Сегодня на факультете функционируют кафедры «Землеустройство», «Геодезия и геоинформатика», «Государственные кадастры» и «Высшая математика». «Государственный налоговый комитет» в целях обеспечения органической связи с производством в сферах землеустройства и земельного кадастра, геодезии и картографии на факультете, обучения студентов и повышения квалификации профессорско-преподавательского состава, укрепления материально-технической базы , а также для организации учебно-производственной практики «Кадастровое агентство» и во взаимодействии с предприятиями и организациями, входящими в его систему, проводятся учебные и научно-исследовательские работы.",
    },
  },
  {
    key: 2,
    navigation_id: "999",
    images: [""],
    positions: [
      [24.20689, -45.439453],
      [15.284185, -43.857422],
      [14.85985, -43.154297],
      [13.410994, -42.802734],
      [10.574222, -51.855469],
      [12.811801, -54.84375],
      [12.46876, -55.722656],
      [12.382928, -59.501953],
      [10.919618, -62.841797],
      [13.923404, -66.796875],
      [14.689881, -66.796875],
      [15.029686, -65.478516],
      [23.483401, -67.324219],
      [25.878994, -57.041016],
      [24.20689, -54.404297],
      [25.641526, -48.076172],
    ],
    uz: {
      name: "11 o'quv binolari",
      videos: ["https://youtu.be/NlWK5kJWFgA"],
      building_info: "",
      deskription:
        "TIQXMMI ning asosiy 4 ta o’quv binosidan biri bo’lib, bu bino 2019-yilda qurilib foydalanishga topshirilgan. O’quv binosi 4 ta qavatdan iborat va shu jumladan ?? ta amaliyot va ?? ta laboratoriya xonalarini o’z ichiga oladi. Binoda bitta fakultet ya’ni “yer resurslarini boshqarish” fakulteti joylashgan. Bu fakultet 1945-yilda Toshkent irrigatsiya va qishloq xoʻjaligini mexanizatsiyalash injenerlari instituti (TIQXMII) tarkibida “Yer tuzish” nomi bilan tashkil etilgan. Fakultet 2004-yildan 2018-yilga qadar “Yerdan foydalanish va yer kadastri” nomi bilan faoliyat koʻrsatgan. Oʻzbekiston Respublikasi Prezidentining 2018-yil 8-maydagi 3702-sonli qaroriga asosan hozirda “Yer resurslarini boshqarish ” nomi bilan faoliyat koʻrsatib kelmoqda. Bugungi kunda fakultetda “Yerdan foydalanish”, “Geodeziya va geoinformatika”, “Davlat kadastrlari” va “Oliy matematika” kafedralari mavjud. Fakultetda yer tuzish va yer kadastri, geodeziya va kartografiya sohalari boʻyicha ishlab chiqarish bilan uzviy aloqalarni taʼminlash, talabalarga bilim berish va professor - oʻqituvchilarning malakasini oshirish hamda moddiy-texnik bazasini mustahkamlash, shuningdek oʻquv va ishlab chiqarish amaliyotlarini tashkil qilish maqsadida “Davlat soliq qo’mitasi huzuridagi kadastr agentligi” va uning tizimidagi korxona va tashkilotlar bilan hamkorlikda oʻquv, ilmiy-tadqiqot ishlari amalga oshirilmoqda.",
    },
    en: {
      name: "11 educational building",
      videos: ["https://youtu.be/NlWK5kJWFgA"],
      building_info: "",
      deskription: `It is one of the 4 main educational buildings of TIQXMMI, and this building was built and commissioned in 2019. The educational building consists of 4 floors and includes ?? ta practice and ?? includes laboratory rooms. There is one faculty in the building, the faculty of "land resources management". This faculty was established in 1945 as part of the Tashkent Institute of Irrigation and Agricultural Mechanization Engineers (TIQXMII) under the name "Earth Construction". From 2004 to 2018, the Faculty operated under the name "Land Use and Land Cadastre". According to the decision of the President of the Republic of Uzbekistan No. 3702 dated May 8, 2018, it is currently operating under the name "Land Resources Management". Today, the faculty has "Land use", "Geodesy and geoinformatics", "State cadastres" and "Higher mathematics" departments. "State tax committee" in order to ensure organic relations with production in the fields of land surveying and land cadastre, geodesy and cartography, to provide education to students and improve the qualifications of professors and teachers, and to strengthen the material and technical base, as well as to organize educational and production practices at the faculty Cadastre Agency" and in cooperation with enterprises and organizations in its system, educational and scientific research works are being carried out.`,
    },
    ru: {
      name: "11 учебные корпуса",
      videos: ["https://youtu.be/NlWK5kJWFgA"],
      building_info: "",
      deskription: `Это один из 4 основных учебных корпусов TIQXMMI, этот корпус был построен и сдан в эксплуатацию в 2019 году. Учебный корпус состоит из 4 этажей и включает в себя ?? та практика и ?? включает лабораторные помещения. В корпусе находится один факультет, факультет «Управление земельными ресурсами». Этот факультет был создан в 1945 году в составе Ташкентского института инженеров ирригации и механизации сельского хозяйства (ТИМИМСХ) под названием «Земляное строительство». С 2004 по 2018 год факультет работал под названием «Землепользование и земельный кадастр». Согласно постановлению Президента Республики Узбекистан №3702 от 8 мая 2018 года, в настоящее время действует под наименованием «Управление земельными ресурсами». Сегодня на факультете функционируют кафедры «Землеустройство», «Геодезия и геоинформатика», «Государственные кадастры» и «Высшая математика». «Государственный налоговый комитет» был создан в целях обеспечения органической связи с производством в области землеустройства и земельного кадастра, геодезии и картографии, обеспечения обучения студентов и повышения квалификации профессорско-преподавательского состава, укрепления материально-технической базы. базе, а также для организации учебных и производственных практик. «Кадастровое агентство» и во взаимодействии с предприятиями и организациями, входящими в его систему, проводятся учебные и научно-исследовательские работы.`,
    },
  },
  {
    key: 3,
    navigation_id: "999",
    images: [""],
    positions: [
      [10.228437, -64.248047],
      [12.382928, -59.326172],
      [12.46876, -55.898438],
      [-1.58183, -36.826172],
      [-5.965754, -36.123047],
      [-8.146243, -41.748047],
      [-12.21118, -36.826172],
      [-7.100893, -23.291016],
      [-10.314919, -18.808594],
      [-14.944785, -18.369141],
      [-19.55979, -29.53125],
      [-17.308688, -32.958984],
      [-18.646245, -36.123047],
      [-19.228177, -35.595703],
      [-21.943046, -35.332031],
      [-24.367114, -41.308594],
      [-11.609193, -55.107422],
      [-6.83917, -55.986328],
      [-4.565474, -51.152344],
      [-0.439449, -55.810547],
      [-1.318243, -58.359375],
      [0.35156, -60.029297],
      [0.79099, -59.414063],
      [1.230374, -59.501953],
      [1.845384, -60.46875],
      [2.547988, -59.326172],
      [6.053161, -63.544922],
    ],
    uz: {
      name: "B o'quv binolari",
      videos: ["https://youtu.be/NlWK5kJWFgA"],
      building_info: "",
      deskription:
        "TIQXMMI ning asosiy 4 ta o’quv binosidan biri bo’lib, bu bino 2019-yilda qurilib foydalanishga topshirilgan. O’quv binosi 4 ta qavatdan iborat va shu jumladan ?? ta amaliyot va ?? ta laboratoriya xonalarini o’z ichiga oladi. Binoda bitta fakultet ya’ni “yer resurslarini boshqarish” fakulteti joylashgan. Bu fakultet 1945-yilda Toshkent irrigatsiya va qishloq xoʻjaligini mexanizatsiyalash injenerlari instituti (TIQXMII) tarkibida “Yer tuzish” nomi bilan tashkil etilgan. Fakultet 2004-yildan 2018-yilga qadar “Yerdan foydalanish va yer kadastri” nomi bilan faoliyat koʻrsatgan. Oʻzbekiston Respublikasi Prezidentining 2018-yil 8-maydagi 3702-sonli qaroriga asosan hozirda “Yer resurslarini boshqarish ” nomi bilan faoliyat koʻrsatib kelmoqda. Bugungi kunda fakultetda “Yerdan foydalanish”, “Geodeziya va geoinformatika”, “Davlat kadastrlari” va “Oliy matematika” kafedralari mavjud. Fakultetda yer tuzish va yer kadastri, geodeziya va kartografiya sohalari boʻyicha ishlab chiqarish bilan uzviy aloqalarni taʼminlash, talabalarga bilim berish va professor - oʻqituvchilarning malakasini oshirish hamda moddiy-texnik bazasini mustahkamlash, shuningdek oʻquv va ishlab chiqarish amaliyotlarini tashkil qilish maqsadida “Davlat soliq qo’mitasi huzuridagi kadastr agentligi” va uning tizimidagi korxona va tashkilotlar bilan hamkorlikda oʻquv, ilmiy-tadqiqot ishlari amalga oshirilmoqda.",
    },
    en: {
      name: "B educational building",
      videos: ["https://youtu.be/NlWK5kJWFgA"],
      building_info: "",
      deskription: `It is one of the 4 main educational buildings of TIQXMMI, and this building was built and commissioned in 2019. The educational building consists of 4 floors and includes ?? ta practice and ?? includes laboratory rooms. There is one faculty in the building, the faculty of "land resources management". This faculty was established in 1945 as part of the Tashkent Institute of Irrigation and Agricultural Mechanization Engineers (TIQXMII) under the name "Earth Construction". From 2004 to 2018, the Faculty operated under the name "Land Use and Land Cadastre". According to the decision of the President of the Republic of Uzbekistan No. 3702 dated May 8, 2018, it is currently operating under the name "Land Resources Management". Today, the faculty has "Land use", "Geodesy and geoinformatics", "State cadastres" and "Higher mathematics" departments. "State tax committee" in order to ensure organic relations with production in the fields of land surveying and land cadastre, geodesy and cartography, to provide education to students and improve the qualifications of professors and teachers, and to strengthen the material and technical base, as well as to organize educational and production practices at the faculty Cadastre Agency" and in cooperation with enterprises and organizations in its system, educational and scientific research works are being carried out.`,
    },
    ru: {
      name: "B учебные корпуса",
      videos: ["https://youtu.be/NlWK5kJWFgA"],
      building_info: "",
      deskription: `Это один из 4 основных учебных корпусов TIQXMMI, этот корпус был построен и сдан в эксплуатацию в 2019 году. Учебный корпус состоит из 4 этажей и включает в себя ?? та практика и ?? включает лабораторные помещения. В корпусе находится один факультет, факультет «Управление земельными ресурсами». Этот факультет был создан в 1945 году в составе Ташкентского института инженеров ирригации и механизации сельского хозяйства (ТИМИМСХ) под названием «Земляное строительство». С 2004 по 2018 год факультет работал под названием «Землепользование и земельный кадастр». Согласно постановлению Президента Республики Узбекистан №3702 от 8 мая 2018 года, в настоящее время действует под наименованием «Управление земельными ресурсами». Сегодня на факультете функционируют кафедры «Землеустройство», «Геодезия и геоинформатика», «Государственные кадастры» и «Высшая математика». «Государственный налоговый комитет» был создан в целях обеспечения органической связи с производством в области землеустройства и земельного кадастра, геодезии и картографии, обеспечения обучения студентов и повышения квалификации профессорско-преподавательского состава, укрепления материально-технической базы. базе, а также для организации учебных и производственных практик. «Кадастровое агентство» и во взаимодействии с предприятиями и организациями, входящими в его систему, проводятся учебные и научно-исследовательские работы.`,
    },
  },
];
